export const ADD_RESOURCE_TOPICS_SUCCESS="ADD_RESOURCE_TOPICS_SUCCESS";
export const ADD_RESOURCE_TOPICS_ERROR ="ADD_RESOURCE_TOPICS_ERROR";
export const ADD_RESOURCE_TOPICS_RESET ="ADD_RESOURCE_TOPICS_RESET";